### ISSUE TITLE
Bad redirect to https://consent.youtube.com/m?...

### ISSUE THREAD

**Issue by imerr** [ArchiveTeam/youtube-grab#11]
```
Archiving item v2:UJFsujreGt8.
1=302 https://www.youtube.com/watch?v=UJFsujreGt8
bad redirect to https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DUJFsujreGt8%26cbrd%3D1&gl=GB&m=0&pc=yt&cm=4&hl=en&src=1
you're likely banned, sleeping for 1800 seconds.
```

**Comment by Rigo-V** [comment]
Same issue. Archiving from a Finnish IP, if that is relevant.

**Comment by CreaZyp154** [comment]
This is due to GDPR regulation. To fix, you will need to set a cookie:
InPrivate:
![image](https://github.com/ArchiveTeam/youtube-grab/assets/73843822/f028b8ee-290d-47ac-ae69-dc56e2001b17)
Cookies accepted (personal session):
![image](https://github.com/ArchiveTeam/youtube-grab/assets/73843822/d2919973-143b-4ad8-8e25-0c611da8a286)

However, setting the cookie manually still redirected to consent.youtube.com for some reasons (and the cookie still say `PENDING`) after clicking `accept all`, so it seems to be a little more complicated...

**Comment by imerr** [comment]
Fixed in https://github.com/ArchiveTeam/youtube-grab/commit/8547a575293cb89db4c97593fbbad06d184b4dea
